# Generated by Django 3.0.1 on 2020-01-02 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160)),
                ('user', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
